### PR TITLE
Math Magicians React Project - Hook Refactor

### PR DESCRIPTION
**Pull request by jmontanholi**
## In this feature branch I implemented the following:

* ### Refactor of Calculator.js component from Class into Functional Component with hooks ✔️

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
Hi @jmontanholi 😃, 

Well done refactoring the class-based component to functional component using hooks. 💯 
Your project is complete!  But there's one thing left to do in order to get the approval 🙏 

- [x] Please fix the broken issues page link in your README file for a completely professional repo 😄 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jmontanholi** [comment]
> Hi @jmontanholi 😃,
> 
> Well done refactoring the class-based component to functional component using hooks. 💯
> Your project is complete! But there's one thing left to do in order to get the approval 🙏
> 
> * [x]  Please fix the broken issues page link in your README file for a completely professional repo 😄
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Sorry, I don't see that, for me, the issues link is working perfectly. Do you possibly know what is causing this?

**Comment by MahmoudBakr23** [comment]
Currently it's taking me to a 404 page not found, please try to copy the link from the repo and update the README FILE locally then push the changes 😊

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
